# ASP.NET Core HTTP file for local probing (VS / Rider / VS Code REST Client)

@host = http://localhost:5080
@tenantA = 11111111-1111-1111-1111-111111111111
@divisionNorth = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

### Health
GET {{host}}/api/health

### Me (dev headers)
GET {{host}}/api/me
X-User-Id: user-editor-north
X-Tenant-Id: {{tenantA}}

### List workflows
GET {{host}}/api/tenants/{{tenantA}}/workflows
X-User-Id: user-editor-north
X-Tenant-Id: {{tenantA}}

### Cross-tenant deny
GET {{host}}/api/tenants/{{tenantA}}/workflows
X-User-Id: user-admin-b
X-Tenant-Id: 22222222-2222-2222-2222-222222222222

### Start enrollment
POST {{host}}/api/tenants/{{tenantA}}/workflows/enrollment
Content-Type: application/json
X-User-Id: user-editor-north
X-Tenant-Id: {{tenantA}}

{
  "divisionId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "title": "Spring enrollment transfer"
}
